# BASIC NUMPY OPERATIONS

In [ ]:
import numpy as np

np.array([1,2,3]) + 0.5



array([1.5, 2.5, 3.5])

In [ ]:
np.random.seed(1234)
A = np.random.randint(1, 10, (3,4))
B = np.random.randint(1, 10, (3,1))

A + B


array([[11, 14, 13, 12],
       [12,  5, 11, 10],
       [10,  2,  7,  2]])

In [ ]:
np.random.seed(4321)
A = np.random.randint(1, 10, (4,4))
B = np.random.randint(1, 10, (2,1))

A + B
#  will raise an error

In [ ]:
np.random.seed(1111)
A = np.random.randint(1, 10, (3,1,4))
B = np.random.randint(1, 10, (2,1))

A + B


array([[[17, 15, 11, 12],
        [12, 10,  6,  7]],

       [[14, 18, 16, 14],
        [ 9, 13, 11,  9]],

       [[18, 16, 12, 16],
        [13, 11,  7, 11]]])

In [ ]:
import numpy as np

A = np.array([3,11,4,5])
B = np.array([5,0,3])

A[:, np.newaxis] - B


array([[-2,  3,  0],
       [ 6, 11,  8],
       [-1,  4,  1],
       [ 0,  5,  2]])

# SOLUTIONS FOR NUMPY QUESTIONS IN LAB

In [ ]:
import numpy as np
import pandas as pd

arr = np.array([[1, 2, 3], [4, 5, 6]])
df = pd.DataFrame(arr, columns=["A", "B", "C"])
print(df)


   A  B  C
0  1  2  3
1  4  5  6


In [ ]:
import numpy as np
import pandas as pd

arr = np.array([1, 2, 3, 4, 5])
df = pd.DataFrame({"values": arr})
df["cumsum"] = np.cumsum(arr)
print(df)


   values  cumsum
0       1       1
1       2       3
2       3       6
3       4      10
4       5      15


In [ ]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
result = np.dot(a, b)
print(result)


[[19 22]
 [43 50]]


In [ ]:
import numpy as np

arr = np.random.randint(1, 10, 15)
unique_values = np.unique(arr)
print(arr)
print(unique_values)


[5 9 8 3 1 5 9 6 6 2 3 1 8 6 7]
[1 2 3 5 6 7 8 9]


In [ ]:
import pandas as pd

df = pd.DataFrame([[1, 2], [3, 4]], columns=["A", "B"])
df_transposed = df.T
print(df_transposed)


   0  1
A  1  3
B  2  4


In [ ]:
import numpy as np

matrix = np.arange(2, 11).reshape(3, 3)
print(matrix)


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [ ]:
import numpy as np

arr = np.zeros(10)
print(arr)
arr[6] = 11
print(arr)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [ ]:
import numpy as np

arr = np.arange(12, 38)
print(arr)


[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [ ]:
import numpy as np

arr1 = np.array([0, 10, 20, 40, 60])
arr2 = np.array([10, 30, 40])
common = np.intersect1d(arr1, arr2)
print(common)


[10 40]


In [ ]:
import numpy as np

arr1 = np.array([0, 10, 20, 40, 60, 80])
arr2 = np.array([10, 30, 40, 50, 70, 90])
diff = np.setdiff1d(arr1, arr2)
print(diff)


[ 0 20 60 80]


In [ ]:
import numpy as np

a = np.array([1, 2])
b = np.array([4, 5])
print(a > b)
print(a >= b)
print(a < b)
print(a <= b)


[False False]
[False False]
[ True  True]
[ True  True]


In [ ]:
import numpy as np

arr = np.eye(3)
print(arr)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np

arr = np.array([[2, 4, 6], [6, 8, 10]])
print(arr[1, 0])


6


In [ ]:
import numpy as np

a = np.array([10, 20, 30])
b = np.array([40, 50, 60])
result = np.column_stack((a, b))
print(result)


[[10 40]
 [20 50]
 [30 60]]


In [ ]:
import numpy as np

arr = np.arange(12).reshape(3, 4)
print(arr)
new_arr = arr * 3
print(new_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]
